@baseUrl = http://localhost:3000/api/watchedMovies

###GET /watchedMovies
GET {{baseUrl}}

###POST /watchedMovies
POST {{baseUrl}}
Content-Type: application/json

{
  "movieId": "9615",
  "title": "The Fast and the Furious: Tokyo Drift"
}

###DELETE /watchedMovies
DELETE {{baseUrl}}
Content-Type: application/json

{
  "_id": "6263df6ebefcfeb0c166ef3b"
}