@baseUrl = http://localhost:3000/api/watchedEpisodes

###GET /watchedEpisodes
GET {{baseUrl}}

###POST /watchedEpisodes
POST {{baseUrl}}
Content-Type: application/json

{
  "episodeId": 484344
}

###DELETE /watchedEpisodes
DELETE {{baseUrl}}
Content-Type: application/json

{
  "_id": "6263de72609bb7425f1c0e18"
}