@baseURL = http://localhost:3000/api

### GET/getPopularSeries
GET {{baseURL}}/getPopularSeries

### GET/topRatedSeries
GET {{baseURL}}/getTopRatedSeries

### GET/seriesOnTv
GET {{baseURL}}/getSeriesOnTv

### GET/popularMovies
GET {{baseURL}}/getPopularMovies

### GET/moviesOnCinema
GET {{baseURL}}/getMoviesOnCinema

### GET/UpcommingMovies
GET {{baseURL}}/getUpcommingMovies